// SPDX-License-Identifier: AGPL-3.0-only

// Package caddy generates and atomically applies HTTPS gateway configuration
// from approved OpenBox routes. Certificate ask endpoints and private-route
// auth middleware belong to later slice tasks; this package only emits markers.
package caddy

import (
	"fmt"
	"net"
	"sort"
	"strings"

	"github.com/openbox-dev/openbox/internal/domain"
	"github.com/openbox-dev/openbox/internal/routes"
)

const generatedHeader = `# Generated by OpenBox from approved database routes.
# Do not edit by hand.
`

// Upstream is a managed instance's private address for reverse_proxy.
type Upstream struct {
	Instance domain.Instance
	Address  string // host only; port comes from the route
}

// UpstreamResolver maps an approved route's instance to a private address.
// Callers supply fakes in tests; production wiring should not require the
// generator to talk to Incus directly.
type UpstreamResolver interface {
	Resolve(ownerID domain.OwnerID, instanceID domain.InstanceID) (Upstream, error)
}

// Generate builds a Caddyfile from the supplied approved routes only.
// It never invents hostnames or upstreams from the resolver alone.
func Generate(approved []domain.Route, resolver UpstreamResolver) ([]byte, error) {
	if resolver == nil {
		return nil, &domain.Error{Code: domain.CodeInvalidArgument, Field: "resolver"}
	}
	if len(approved) == 0 {
		return []byte(generatedHeader), nil
	}

	sorted := append([]domain.Route(nil), approved...)
	sort.SliceStable(sorted, func(i, j int) bool {
		if sorted[i].Hostname != sorted[j].Hostname {
			return sorted[i].Hostname < sorted[j].Hostname
		}
		return sorted[i].ID < sorted[j].ID
	})

	var body strings.Builder
	body.WriteString(generatedHeader)

	for _, route := range sorted {
		upstream, err := resolver.Resolve(route.OwnerID, route.InstanceID)
		if err != nil {
			return nil, err
		}
		if err := routes.ValidateManagedTarget(route.OwnerID, &upstream.Instance); err != nil {
			return nil, err
		}
		addr := strings.TrimSpace(upstream.Address)
		if addr == "" {
			return nil, &domain.Error{Code: domain.CodeInvalidArgument, Field: "address"}
		}
		if _, _, err := net.SplitHostPort(addr); err == nil {
			// Address must be host-only; port comes from the route.
			return nil, &domain.Error{Code: domain.CodeInvalidArgument, Field: "address"}
		}
		if err := routes.ValidateTargetPort(route.TargetPort); err != nil {
			return nil, err
		}

		authMarker := "none"
		if route.Visibility == domain.RoutePrivate {
			authMarker = "required"
		}
		body.WriteByte('\n')
		fmt.Fprintf(&body, "# openbox:route_id=%s visibility=%s auth=%s\n", route.ID, route.Visibility, authMarker)
		fmt.Fprintf(&body, "%s {\n", route.Hostname)
		fmt.Fprintf(&body, "\treverse_proxy %s:%d\n", addr, route.TargetPort)
		body.WriteString("}\n")
	}
	return []byte(body.String()), nil
}
